---
title: "NHSBSA Producing Quality Analysis Playbook"
description: ""
title-block-banner: true
listing:
  type: grid
  contents: "guidance/*/index.qmd"
  sort: "path"
format:
  html:
    html-math-method: katex
    css: styles.css
    embed-resources: true
    include-before-body: skip-link.html
    include-after-body: post-load-accessibility-fixes.html
toc: false
---

This playbook sets out the NHSBSA’s expectations for planning and doing analysis. 

It provides direction and guidance for everyone at the NHSBSA. It is especially for: 

- Directors and Heads of Service to ensure appropriate governance of analysis in their areas.  

- Commissioners, users, analysts and analytical assurers. This includes non-analysts and third-party suppliers.  

It covers all analysis and datasets. This includes analysis and data published externally and used for internal decisions. It also includes analysis/data given to our sponsors/partners.

::: {.callout-note title="Examples of Analytical Outputs" appearance="minimal" icon=false}
<br>
**Data requests** – responses to Freedom of Information (FOI) requests, Parliamentary Questions (PQs), data for sponsors and other adhoc requests.

**Data products and reports** – for colleagues in the NHS, or external partners, including performance data, customer insight reports, operational forecasts and cost/benfit evaluations.

**Open datasets** – such as those on the [Open Data Portal (ODP)](https://opendata.nhsbsa.net/).

**Official Statistics** – including [publications and data releases](https://www.nhsbsa.nhs.uk/statistical-collections).

**Data Science releases** - including [articles, reports](https://www.nhsbsa.nhs.uk/data-science-projects), [models and code](https://www.nhsbsa.nhs.uk/data-and-analytics-code-repositories).
:::

This will ensure quality and consistency of analysis and support well-informed decisions. 

This Playbook is based on:
 
- [Government functional standard 010: analysis](https://www.gov.uk/government/publications/government-analysis-functional-standard--2/government-functional-standard-govs-010-analysis)

- [The Aqua Book: guidance on producing quality analysis for government](https://www.gov.uk/guidance/the-aqua-book) 

- [Code of Practice for Statistics](https://code.statisticsauthority.gov.uk/)

 

The [Green Book](https://www.gov.uk/government/publications/the-green-book-appraisal-and-evaluation-in-central-government) and [Magenta Book](https://www.gov.uk/government/publications/the-magenta-book)  also cover analysis involving appraisal and evaluation. 

::: {.callout-note title="Roles" appearance="minimal" icon=false}
<br>
**Commissioner** – the person requesting the analysis. This could be an internal team, external partner or sponsor such as DHSC or NHS England.

**Analyst** – the person planning, undertaking and documenting the analysis. This includes Data Analysts and Performance Analysts. It also includes Customer Insight Officers, Statistical Officers, Statisticians and Data Scientists.

**Critical friend/analytical assurer** – the person who signs off that the analysis is fit-for-purpose. This person should not be delivering the analysis. They are usually a Senior Analyst but need not always be an analyst. Ideally, they will have prior knowledge of the subject matter and/or techniques being used.

**Senior Responsible Owner (SRO)** – the person who takes responsibility of a ‘Business-Critical Model’ resulting from the analysis throughout its lifecycle. The SRO signs-off that a model is fit-for-purpose prior to its use. This may be the Commissioner.
:::

